// Copyright 2019. PingCAP, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// See the License for the specific language governing permissions and
// limitations under the License.

package v1beta1

import (
	tidb "github.com/pingcap/tidb-operator/pkg/apiserver/apis/tidb"
	conversion "k8s.io/apimachinery/pkg/conversion"
)

// Convert_v1alpha1_FooSpec_To_tidb_FooSpec is an autogenerated conversion function.
func Convert_v1alpha1_FooSpec_To_tidb_FooSpec(in *FooSpec, out *tidb.FooSpec, s conversion.Scope) error {
	out.Replicas = in.Replicas
	out.ConfigMapName = in.ConfigMapName
	return nil
}

// Convert_tidb_FooSpec_To_v1alpha1_FooSpec is an autogenerated conversion function.
func Convert_tidb_FooSpec_To_v1alpha1_FooSpec(in *tidb.FooSpec, out *FooSpec, s conversion.Scope) error {
	out.Replicas = in.Replicas
	out.ConfigMapName = in.ConfigMapName
	return nil
}
