apiVersion: v1
kind: ConfigMap
metadata:
{{- if .Values.enableConfigMapRollout }}
  name: {{ template "cluster.name" . }}-tikv-{{ include "tikv-configmap.data" . | sha256sum | trunc 8 }}
{{- else }}
  name: {{ template "cluster.name" . }}-tikv
{{- end }}
  labels:
    app.kubernetes.io/name: {{ template "chart.name" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: tikv
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+"  "_" }}
data:
{{ include "tidb-configmap.data-digest" . | indent 2 }}
